baseURL = "https://www.apriendeau.com/"
languageCode = "en-us"
title = "My name is Austin"
theme = "cactus"

contentDir = "content"
publishDir = "docs"
copyright = "austin riendeau " # cactus will use title if copyright is not set
disqusShortname = "apriendeau" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"
# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  gravatar = "austin@apriendeau.com"
  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "My name is Austin. I live with ADHD. I dabble in keebs, music and programming."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 10 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/apriendeau" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/apriendeau"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/apriendeau"
  [[params.social]]
    name = "email"
    link = "austin@apriendeau.com"  # no need for "mailto:" in the head
